const NOTION_VERSION = "2022-06-28";

const DATABASES = [
  { key: "projects", envKey: "NOTION_PROJECTS_DATABASE_ID" },
  { key: "resources", envKey: "NOTION_RESOURCES_DATABASE_ID" },
  { key: "allocations", envKey: "NOTION_ALLOCATIONS_DATABASE_ID" },
  { key: "changes", envKey: "NOTION_CHANGES_DATABASE_ID" },
  { key: "signoffs", envKey: "NOTION_SIGNOFFS_DATABASE_ID" },
];

function json(res, statusCode, body) {
  res.statusCode = statusCode;
  res.setHeader("content-type", "application/json");
  res.end(JSON.stringify(body));
}

async function readBody(req) {
  if (req.body && typeof req.body === "object") return req.body;
  if (typeof req.body === "string") return JSON.parse(req.body || "{}");

  const chunks = [];
  for await (const chunk of req) chunks.push(chunk);
  const raw = Buffer.concat(chunks).toString("utf8");
  return raw ? JSON.parse(raw) : {};
}

async function notionRequest(path, options = {}) {
  const token = process.env.NOTION_API_KEY;
  if (!token) {
    throw new Error("NOTION_API_KEY is not configured");
  }

  const response = await fetch(`https://api.notion.com/v1${path}`, {
    ...options,
    headers: {
      authorization: `Bearer ${token}`,
      "content-type": "application/json",
      "notion-version": NOTION_VERSION,
      ...(options.headers || {}),
    },
  });

  const payload = await response.json().catch(() => ({}));
  if (!response.ok) {
    const message = payload.message || `Notion request failed with ${response.status}`;
    throw new Error(message);
  }

  return payload;
}

function plainText(richText = []) {
  return richText.map((item) => item.plain_text || item.text?.content || "").join("");
}

function propertyValue(property) {
  if (!property) return null;

  switch (property.type) {
    case "title":
      return plainText(property.title);
    case "rich_text":
      return plainText(property.rich_text);
    case "select":
      return property.select?.name ?? null;
    case "multi_select":
      return property.multi_select.map((item) => item.name);
    case "status":
      return property.status?.name ?? null;
    case "number":
      return property.number;
    case "checkbox":
      return property.checkbox;
    case "date":
      return property.date;
    case "people":
      return property.people.map((person) => person.name || person.id);
    case "relation":
      return property.relation.map((item) => item.id);
    case "url":
      return property.url;
    case "email":
      return property.email;
    case "phone_number":
      return property.phone_number;
    default:
      return null;
  }
}

function normalizePage(page) {
  const properties = Object.fromEntries(
    Object.entries(page.properties || {}).map(([name, property]) => [name, propertyValue(property)]),
  );

  return {
    id: page.id,
    url: page.url,
    createdTime: page.created_time,
    lastEditedTime: page.last_edited_time,
    properties,
  };
}

async function queryDatabase(databaseId) {
  const payload = await notionRequest(`/databases/${databaseId}/query`, {
    method: "POST",
    body: JSON.stringify({ page_size: 50 }),
  });

  return payload.results.map(normalizePage);
}

async function syncDatabases() {
  const configured = DATABASES.filter((database) => process.env[database.envKey]);
  const results = await Promise.all(
    configured.map(async (database) => ({
      key: database.key,
      envKey: database.envKey,
      rows: await queryDatabase(process.env[database.envKey]),
    })),
  );

  return {
    mode: "notion-live-sync",
    syncedAt: new Date().toISOString(),
    databases: Object.fromEntries(results.map((result) => [result.key, result.rows])),
    configured: configured.map((database) => database.key),
    missing: DATABASES.filter((database) => !process.env[database.envKey]).map((database) => database.envKey),
  };
}

async function createReport(body) {
  const dataSourceId = process.env.NOTION_REPORTS_DATABASE_ID;
  if (!dataSourceId) {
    throw new Error("NOTION_REPORTS_DATABASE_ID is not configured");
  }

  return notionRequest("/pages", {
    method: "POST",
    body: JSON.stringify({
      parent: { database_id: dataSourceId },
      properties: {
        Name: {
          title: [{ text: { content: body.title || "OzzyPM portfolio brief" } }],
        },
        Summary: {
          rich_text: [{ text: { content: body.summary || "Generated by OzzyPM." } }],
        },
        "Risk Level": {
          select: { name: body.riskLevel || "Medium" },
        },
        "Generated At": {
          date: { start: new Date().toISOString() },
        },
      },
    }),
  });
}

module.exports = async function handler(req, res) {
  res.setHeader("access-control-allow-origin", "*");
  res.setHeader("access-control-allow-methods", "GET,POST,OPTIONS");
  res.setHeader("access-control-allow-headers", "content-type");

  if (req.method === "OPTIONS") {
    res.statusCode = 204;
    res.end();
    return;
  }

  try {
    if (!process.env.NOTION_API_KEY) {
      return json(res, 200, {
        mode: "notion-not-configured",
        message: "Set NOTION_API_KEY and the Notion database ID environment variables on the server.",
        requiredEnv: ["NOTION_API_KEY", ...DATABASES.map((database) => database.envKey), "NOTION_REPORTS_DATABASE_ID"],
      });
    }

    if (req.method === "GET") {
      return json(res, 200, await syncDatabases());
    }

    if (req.method === "POST") {
      const body = await readBody(req);
      if (body.action === "create-report") {
        return json(res, 200, await createReport(body));
      }

      return json(res, 200, await syncDatabases());
    }

    return json(res, 405, { error: "Method not allowed" });
  } catch (error) {
    return json(res, 500, { error: error.message });
  }
};
